import io
from reportlab.lib import colors
from reportlab.lib.pagesizes import letter
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle

def generate_executive_pdf(
    decisions, exposures, narrative, total_spend, high_risk_count,
    medium_risk_count, decision_count, estimated_savings, ebitda_at_risk, vendor_count
) -> io.BytesIO:
    buffer = io.BytesIO()
    doc = SimpleDocTemplate(buffer, pagesize=letter)
    styles = getSampleStyleSheet()
    
    # Custom Styles
    title_style = styles['Heading1']
    title_style.alignment = 1 # Center
    
    subtitle_style = styles['Heading2']
    subtitle_style.textColor = colors.HexColor("#4F46E5")
    
    normal_style = styles['Normal']
    normal_style.fontSize = 11
    normal_style.leading = 14
    
    elements = []
    
    # Title
    elements.append(Paragraph("CADE - Capital Allocation Board Report", title_style))
    elements.append(Spacer(1, 20))
    
    # Executive Summary (AI Narrative)
    elements.append(Paragraph("Executive Summary", subtitle_style))
    elements.append(Spacer(1, 10))
    if narrative:
        elements.append(Paragraph(narrative, normal_style))
    else:
        elements.append(Paragraph("No narrative generated.", normal_style))
    elements.append(Spacer(1, 20))
    
    # KPIs Table
    elements.append(Paragraph("Key Performance Indicators (KPIs)", subtitle_style))
    elements.append(Spacer(1, 10))
    
    kpi_data = [
        ["Total Spend Analyzed", f"${total_spend:,.0f}"],
        ["Total Vendors", str(vendor_count)],
        ["Estimated Savings Identified", f"${estimated_savings:,.0f}"],
        ["EBITDA at Risk (10% Shock)", f"${ebitda_at_risk:,.0f}"],
        ["High Risk Vendors", str(high_risk_count)],
        ["Total Recommendations", str(decision_count)]
    ]
    
    kpi_table = Table(kpi_data, colWidths=[200, 150])
    kpi_table.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, -1), colors.HexColor("#F9FAFB")),
        ('TEXTCOLOR', (0, 0), (0, -1), colors.HexColor("#374151")),
        ('TEXTCOLOR', (1, 0), (1, -1), colors.HexColor("#111827")),
        ('ALIGN', (0, 0), (0, -1), 'LEFT'),
        ('ALIGN', (1, 0), (1, -1), 'RIGHT'),
        ('FONTNAME', (0, 0), (0, -1), 'Helvetica'),
        ('FONTNAME', (1, 0), (1, -1), 'Helvetica-Bold'),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 8),
        ('TOPPADDING', (0, 0), (-1, -1), 8),
        ('GRID', (0, 0), (-1, -1), 1, colors.HexColor("#E5E7EB"))
    ]))
    elements.append(kpi_table)
    elements.append(Spacer(1, 25))
    
    # Top Vendors Table
    elements.append(Paragraph("Top Exposure Risk Ranked", subtitle_style))
    elements.append(Spacer(1, 10))
    
    exposures.sort(key=lambda x: x.worst_case_exposure, reverse=True)
    top_exposures = exposures[:10]
    
    table_data = [["Vendor", "Category", "Annual Spend", "Exposure Risk"]]
    for exp in top_exposures:
        table_data.append([
            exp.vendor_id,
            exp.category,
            f"${exp.annual_spend:,.0f}",
            f"${exp.worst_case_exposure:,.0f}"
        ])
        
    vendor_table = Table(table_data, colWidths=[120, 120, 100, 100])
    vendor_table.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor("#4F46E5")),
        ('TEXTCOLOR', (0, 0), (-1, 0), colors.whitesmoke),
        ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
        ('ALIGN', (2, 0), (-1, -1), 'RIGHT'),
        ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
        ('FONTNAME', (0, 1), (-1, -1), 'Helvetica'),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 6),
        ('TOPPADDING', (0, 0), (-1, -1), 6),
        ('GRID', (0, 0), (-1, -1), 1, colors.HexColor("#E5E7EB")),
        ('ROWBACKGROUNDS', (0, 1), (-1, -1), [colors.white, colors.HexColor("#F9FAFB")])
    ]))
    
    elements.append(vendor_table)
    elements.append(Spacer(1, 20))
    
    # Footer
    elements.append(Paragraph("Generated by CADE (Capital Allocation Decision Engine)", styles['Italic']))
    
    doc.build(elements)
    buffer.seek(0)
    return buffer
